In [1]:
import numpy as np
import random
import pandas as pd
import functools

In [2]:
data = {'name': ['Christine', 'Susan', 'Margaret', 'Judith', 'Jennifer', 'Mary', 'Elizabeth', 'Patricia', 'Linda', 
'Barbara', 'Lynette', 'Anne', 'Karen', 'Helen', 'Diane', 'Sandra', 'Wendy', 'Janet', 'Heather', 
'Pamela', 'Carol', 'Janice', 'Julie', 'Suzanne', 'Lorraine', 'Dianne', 'Marilyn', 'Rosemary', 'Sheryl', 
'Kathleen', 'John', 'David', 'Peter', 'Michael', 'Robert', 'Paul', 'Stephen', 'Kevin', 'Christopher', 
'Brian', 'William', 'Ian', 'Mark', 'Richard', 'Alan', 'Bruce', 'Geoffrey', 'Raymond', 'Gary', 'Anthony', 
'Graham', 'Philip', 'Barry', 'Colin', 'Trevor', 'Kenneth', 'Ross', 'Grant', 'Keith', 'Allan'], 
        'gender': ['w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 
'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 
'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm', 'm'], 
        'likes_women': ['n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 
'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 
'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y'], 
        'likes_men': ['y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 
'n', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 
'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y'], 
        'preference': ['h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'g', 'g', 'g', 'g', 'g', 
'g', 'g', 'g', 'g', 'g', 'b', 'b', 'b', 'b', 'b', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 'h', 
'h', 'h', 'h', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'b', 'b', 'b', 'b', 'b']}

In [3]:
df = pd.DataFrame(data, columns = ['name', 'gender', 'likes_women', 'likes_men', 'preference'])
df['match_type'] = df['gender'] + '-' + df['preference']

In [4]:
def matching_selection():
    match_types = ['wny', 'myn', 'wyn', 'mny', 'wyy', 'myy']
    match_type = random.choice(match_types)
    return match_type

In [5]:
def data_selection(match_type):
    match_for_df = []
    match_with_df = [] 
    
    if match_type =='wny': 
        match_for_df = df[(df['gender'] == 'w') & (df['likes_women'] == 'n') & (df['likes_men'] == 'y')]
        match_with_df = df[(df['gender'] == 'm') & (df['likes_women'] == 'y')]
        return match_for_df, match_with_df
    
    elif match_type == 'myn':
        match_for_df = df[(df['gender'] == 'm') & (df['likes_women'] == 'y') & (df['likes_men'] == 'n')]
        match_with_df = df[(df['gender'] == 'w') & (df['likes_men'] == 'y')]
        return match_for_df, match_with_df
    
    elif match_type == 'wyn':
        match_for_df = df[(df['gender'] == 'w') & (df['likes_women'] == 'y') & (df['likes_men'] == 'n')]
        match_with_df = df[(df['gender'] == 'w') & (df['likes_women'] == 'y')]
        return match_for_df, match_with_df
    
    elif match_type == 'mny':
        match_for_df = df[(df['gender'] == 'm') & (df['likes_women'] == 'n') & (df['likes_men'] == 'y')]
        match_with_df = df[(df['gender'] == 'm') & (df['likes_men'] == 'y')]
        return match_for_df, match_with_df
    
    elif match_type == 'wyy':
        match_for_df = df[(df['gender'] == 'w') & (df['likes_women'] == 'y') & (df['likes_men'] == 'y')]
        match_with_df = df[df['likes_women'] == 'y']
        return match_for_df, match_with_df

    elif match_type == 'myy':
        match_for_df = df[(df['gender'] == 'm') & (df['likes_women'] == 'y') & (df['likes_men'] == 'y')]
        match_with_df = df[df['likes_men'] == 'y']
        return match_for_df, match_with_df
    else:
        pass

In [6]:
def user_matching(match_for_df, match_with_df):
    n = 5
    matched = []
    match_for = match_for_df['name'].tolist()
    match_with = match_with_df['name'].tolist()
    
    while len(match_for) >= n and len(match_with) >= n:
        batch_1 = match_for[:n]
        batch_2 = [user for user in match_with if user not in batch_1]
        batch_2 = random.sample(batch_2, n)
        for i in range(n):
            matched.append(batch_1[i])
            matched.append(batch_2)
        for i in range(n):
            matched.append(batch_2[i])
            matched.append(batch_1)
        remove_batches = batch_1 + batch_2
        match_for = [user for user in match_for if user not in remove_batches]
        match_with = [user for user in match_with if user not in remove_batches]
    return match_for_df, match_with_df, matched, remove_batches

In [7]:
def main():
 
    match_type = matching_selection()
    match_for_df, match_with_df = data_selection(match_type)
    match_for_df, match_with_df, matched, remove_batches = user_matching(match_for_df, match_with_df)
    
    return match_for_df, match_with_df, matched

In [8]:
main()

(           name gender likes_women likes_men preference match_type
 30         John      m           y         n          h        m-h
 31        David      m           y         n          h        m-h
 32        Peter      m           y         n          h        m-h
 33      Michael      m           y         n          h        m-h
 34       Robert      m           y         n          h        m-h
 35         Paul      m           y         n          h        m-h
 36      Stephen      m           y         n          h        m-h
 37        Kevin      m           y         n          h        m-h
 38  Christopher      m           y         n          h        m-h
 39        Brian      m           y         n          h        m-h
 40      William      m           y         n          h        m-h
 41          Ian      m           y         n          h        m-h
 42         Mark      m           y         n          h        m-h
 43      Richard      m           y         n          h        m-h
 44         Alan      m           y         n          h        m-h,
          name gender likes_women likes_men preference match_type
 0   Christine      w           n         y          h        w-h
 1       Susan      w           n         y          h        w-h
 2    Margaret      w           n         y          h        w-h
 3      Judith      w           n         y          h        w-h
 4    Jennifer      w           n         y          h        w-h
 5        Mary      w           n         y          h        w-h
 6   Elizabeth      w           n         y          h        w-h
 7    Patricia      w           n         y          h        w-h
 8       Linda      w           n         y          h        w-h
 9     Barbara      w           n         y          h        w-h
 10    Lynette      w           n         y          h        w-h
 11       Anne      w           n         y          h        w-h
 12      Karen      w           n         y          h        w-h
 13      Helen      w           n         y          h        w-h
 14      Diane      w           n         y          h        w-h
 25     Dianne      w           y         y          b        w-b
 26    Marilyn      w           y         y          b        w-b
 27   Rosemary      w           y         y          b        w-b
 28     Sheryl      w           y         y          b        w-b
 29   Kathleen      w           y         y          b        w-b,
 ['John',
  ['Christine', 'Diane', 'Patricia', 'Kathleen', 'Linda'],
  'David',
  ['Christine', 'Diane', 'Patricia', 'Kathleen', 'Linda'],
  'Peter',
  ['Christine', 'Diane', 'Patricia', 'Kathleen', 'Linda'],
  'Michael',
  ['Christine', 'Diane', 'Patricia', 'Kathleen', 'Linda'],
  'Robert',
  ['Christine', 'Diane', 'Patricia', 'Kathleen', 'Linda'],
  'Christine',
  ['John', 'David', 'Peter', 'Michael', 'Robert'],
  'Diane',
  ['John', 'David', 'Peter', 'Michael', 'Robert'],
  'Patricia',
  ['John', 'David', 'Peter', 'Michael', 'Robert'],
  'Kathleen',
  ['John', 'David', 'Peter', 'Michael', 'Robert'],
  'Linda',
  ['John', 'David', 'Peter', 'Michael', 'Robert'],
  'Paul',
  ['Judith', 'Susan', 'Helen', 'Mary', 'Sheryl'],
  'Stephen',
  ['Judith', 'Susan', 'Helen', 'Mary', 'Sheryl'],
  'Kevin',
  ['Judith', 'Susan', 'Helen', 'Mary', 'Sheryl'],
  'Christopher',
  ['Judith', 'Susan', 'Helen', 'Mary', 'Sheryl'],
  'Brian',
  ['Judith', 'Susan', 'Helen', 'Mary', 'Sheryl'],
  'Judith',
  ['Paul', 'Stephen', 'Kevin', 'Christopher', 'Brian'],
  'Susan',
  ['Paul', 'Stephen', 'Kevin', 'Christopher', 'Brian'],
  'Helen',
  ['Paul', 'Stephen', 'Kevin', 'Christopher', 'Brian'],
  'Mary',
  ['Paul', 'Stephen', 'Kevin', 'Christopher', 'Brian'],
  'Sheryl',
  ['Paul', 'Stephen', 'Kevin', 'Christopher', 'Brian'],
  'William',
  ['Jennifer', 'Marilyn', 'Anne', 'Elizabeth', 'Rosemary'],
  'Ian',
  ['Jennifer', 'Marilyn', 'Anne', 'Elizabeth', 'Rosemary'],
  'Mark',
  ['Jennifer', 'Marilyn', 'Anne', 'Elizabeth', 'Rosemary'],
  'Richard',
  ['Jennifer', 'Marilyn', 'Anne', 'Elizabeth', 'Rosemary'],
  'Alan',
  ['Jennifer', 'Marilyn', 'Anne', 'Elizabeth', 'Rosemary'],
  'Jennifer',
  ['William', 'Ian', 'Mark', 'Richard', 'Alan'],
  'Marilyn',
  ['William', 'Ian', 'Mark', 'Richard', 'Alan'],
  'Anne',
  ['William', 'Ian', 'Mark', 'Richard', 'Alan'],
  'Elizabeth',
  ['William', 'Ian', 'Mark', 'Richard', 'Alan'],
  'Rosemary',
  ['William', 'Ian', 'Mark', 'Richard', 'Alan']])